### ISSUE TITLE
debug mode in `test.sh` gives error (-5:Bad argument) in function 'line'

### ISSUE THREAD

**Issue by fabrizioschiano** [mrnabati/CenterFusion#42]
I am trying to visualize the intermediate results of testing. As @mrnabati pointed out in [this issue](https://github.com/mrnabati/CenterFusion/issues/8#issuecomment-740428960) I tried to enable debug by putting `--debug 4 \` in the `test.sh` file. However, I get the following error:
```
Traceback (most recent call last):
  File "test.py", line 224, in <module>
    prefetch_test(opt)
  File "test.py", line 131, in prefetch_test
    ret = detector.run(pre_processed_images)
  File "/home/fabrizioschiano/repositories/CenterFusion/src/lib/detector.py", line 159, in run
    self.show_results(self.debugger, image, results)
  File "/home/fabrizioschiano/repositories/CenterFusion/src/lib/detector.py", line 435, in show_results
    debugger.add_bird_view(
  File "/home/fabrizioschiano/repositories/CenterFusion/src/lib/utils/debugger.py", line 424, in add_bird_view
    cv2.line(bird_view, (rect[e[0]][0], rect[e[0]][1]),
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type

```

Did anyone experience this issue? 

Thanks!

**Comment by fabrizioschiano** [comment]
It now works as you can also see from the following screenshot. As you can see, many pictures are generated for each sample. Therefore, next step would be to understand exactly what are all the pictures generated in the debug folder. 

![image](https://user-images.githubusercontent.com/3736380/137508057-5a86a8c9-f907-4714-9adb-b0c1964b1d34.png)
