### ISSUE TITLE
run demo with custom image+radar data

### ISSUE THREAD

**Issue by LongfeiDE** [mrnabati/CenterFusion#58]
Dear Authors,

I would like to test your code with my own data gathered from a combination of camera and radar.
Could you please enlighten me how to preprocess the data and arrange the arguments of demo.py or test.py?

Thanks a lot!

**Comment by ryontang** [comment]
hi, how is your work going?

**Comment by stanny880913** [comment]
> Dear Authors,
> 
> I would like to test your code with my own data gathered from a combination of camera and radar. Could you please enlighten me how to preprocess the data and arrange the arguments of demo.py or test.py?
> 
> Thanks a lot!

Hello，Do you Success? I meet the same problem!
If you finished it, could you please help me?
Thank you

**Comment by UmangBDhanani** [comment]
Hello @LongfeiDE, @ryontang Have you found the solution to your problem to test the code on personal camera radar dataset? Any help would be appreciable. 
Thank you.

**Comment by HPlank** [comment]
> Hello [@LongfeiDE](https://github.com/LongfeiDE), [@ryontang](https://github.com/ryontang) Have you found the solution to your problem to test the code on personal camera radar dataset? Any help would be appreciable. Thank you.

hello， @LongfeiDE @stanny880913 @UmangBDhanani @ryontang  Do you work success? 
Any help would be appreciable.
Thank you.

**Comment by ljbosma** [comment]
I am also trying to train it on a custom-made dataset. I have been able to sort everything out, but I run into the following error now:
Traceback (most recent call last):
  File "main.py", line 140, in <module>
    main(opt)
  File "main.py", line 84, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/docker/CenterFusion/src/lib/trainer.py", line 406, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/docker/CenterFusion/src/lib/trainer.py", line 205, in run_epoch
    self.debug(batch, output, iter_id, dataset=data_loader.dataset)
  File "/home/docker/CenterFusion/src/lib/trainer.py", line 251, in debug
    dets = fusion_decode(output, K=opt.K, opt=opt)
  File "/home/docker/CenterFusion/src/lib/model/decode.py", line 161, in fusion_decode
    dep_sec_mask = torch.tensor(dep_sec_mask, device=dep_sec.device).unsqueeze(0).unsqueeze(0).unsqueeze(3)
UnboundLocalError: local variable 'dep_sec_mask' referenced before assignment
(centerfusion) docker@50d3d66605f7:~/CenterFusion/src$ 

I assume that I should not try to change any of the code written by the authors. Has anyone run into this problem?
