### ISSUE TITLE
AssertionError: Database version not found: ../data/nuscenes/v1.0-trainval

### ISSUE THREAD

**Issue by upupgitup** [mrnabati/CenterFusion#77]
when I used test.sh, I set **--val_split test,** but when I finished, it was **AssertionError: Database version not found: ../data/nuscenes/v1.0-trainval**

**Converting nuscenes format...
Traceback (most recent call last):
  File "tools/nuscenes-devkit/python-sdk/nuscenes/eval/detection/evaluate.py", line 299, in <module>
    nusc_ = NuScenes(version=version_, verbose=verbose_, dataroot=dataroot_)
  File "/home/gjp/anaconda3/envs/env1/lib/python3.7/site-packages/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: ../data/nuscenes/v1.0-trainval**

how to fix this problem?

**Comment by upupgitup** [comment]
Can you help me，bro？ @mrnabati

**Comment by upupgitup** [comment]
But when I use mini_val to test, there is no problem, I really don't know what to do, please help me

**Comment by followerlan** [comment]
> when I used test.sh, I set **--val_split test,** but when I finished, it was **AssertionError: Database version not found: ../data/nuscenes/v1.0-trainval**
> 
> **Converting nuscenes format... Traceback (most recent call last): File "tools/nuscenes-devkit/python-sdk/nuscenes/eval/detection/evaluate.py", line 299, in nusc_ = NuScenes(version=version_, verbose=verbose_, dataroot=dataroot_) File "/home/gjp/anaconda3/envs/env1/lib/python3.7/site-packages/nuscenes/nuscenes.py", line 62, in init assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root) AssertionError: Database version not found: ../data/nuscenes/v1.0-trainval**
> 
> how to fix this problem?

I also meet the some question, did you solve it?

**Comment by ADDED598** [comment]
> > when I used test.sh, I set **--val_split test,** but when I finished, it was **AssertionError: Database version not found: ../data/nuscenes/v1.0-trainval**
> > **Converting nuscenes format... Traceback (most recent call last): File "tools/nuscenes-devkit/python-sdk/nuscenes/eval/detection/evaluate.py", line 299, in nusc_ = NuScenes(version=version_, verbose=verbose_, dataroot=dataroot_) File "/home/gjp/anaconda3/envs/env1/lib/python3.7/site-packages/nuscenes/nuscenes.py", line 62, in init assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root) AssertionError: Database version not found: ../data/nuscenes/v1.0-trainval**
> > how to fix this problem?
> 
> I also meet the some question, did you solve it?

have you solved, bro?
