### ISSUE TITLE
error when train.sh

### ISSUE THREAD

**Issue by renchao-666** [mrnabati/CenterFusion#83]
Creating model...
Using node type: (<class 'model.networks.dla.DeformConv'>, <class 'model.networks.dla.DeformConv'>)
Warning: No ImageNet pretrain!!
Traceback (most recent call last):
  File "main.py", line 140, in <module>
    main(opt)
  File "main.py", line 42, in main
    model = create_model(opt.arch, opt.heads, opt.head_conv, opt=opt)
  File "/CenterFusion/src/lib/model/model.py", line 28, in create_model
    model = model_class(num_layers, heads=head, head_convs=head_conv, opt=opt)
  File "/CenterFusion/src/lib/model/networks/dla.py", line 609, in __init__
    self.dla_up = DLAUp(
  File "/CenterFusion/src/lib/model/networks/dla.py", line 562, in __init__
    IDAUp(channels[j], in_channels[j:],
  File "/CenterFusion/src/lib/model/networks/dla.py", line 526, in __init__
    proj = node_type[0](c, o)
  File "/CenterFusion/src/lib/model/networks/dla.py", line 513, in __init__
    self.conv = DCN(chi, cho, kernel_size=(3,3), stride=1, padding=1, dilation=1, deformable_groups=1)
TypeError: 'NoneType' object is not callable

**Comment by renchao-666** [comment]
THANKS FOR YOUR ATTANTION!

**Comment by renchao-666** [comment]
I find ：
https://github.com/xingyizhou/CenterTrack/issues/240
